spring:
  datasource:
    url: jdbc:mysql://localhost:3306/kospot-test?serverTimezone=UTC
    username: root
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create

    properties:
      hibernate:
        format_sql: true  # SQL 포맷 정렬 여부
        highlight_sql: true  # SQL 하이라이트 여부
        use_sql_comments: true
        show-sql: true


#  security:
#    oauth2:
#      client:
#        registration:
#          google:
#            client-id: { YOUR_CLIENT_ID }
#            client-secret: { YOUR_CLIENT_SECRET }
#            scope: email
#          naver:
#            client-id: { YOUR_CLIENT_ID }
#            client-secret: { YOUR_CLIENT_SECRET }
#            scope: email
#            client-name: Naver
#            authorization-grant-type: authorization_code
#            redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"
#          kakao:
#            client-id: { YOUR_CLIENT_ID }
#            client-secret: { YOUR_CLIENT_SECRET }
#            scope: account_email
#            client-name: Kakao
#            authorization-grant-type: authorization_code
#            redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"
#            client-authentication-method: client_secret_post
#
#
#        provider:
#          google:
#            authorization-uri: https://accounts.google.com/o/oauth2/v2/auth
#        token-uri: https://oauth2.googleapis.com/token
#        user-info-uri: https://www.googleapis.com/oauth2/v3/userinfo
#        user-name-attribute: sub
#          naver:
#            authorization_uri: https://nid.naver.com/oauth2.0/authorize
#            token_uri: https://nid.naver.com/oauth2.0/token
#            user-info-uri: https://openapi.naver.com/v1/nid/me
#            user_name_attribute: response
#          kakao:
#            authorization-uri: https://kauth.kakao.com/oauth/authorize
#        token-uri: https://kauth.kakao.com/oauth/token
#        user-info-uri: https://kapi.kakao.com/v2/user/me
#        user-name-attribute: id

# 서버 포트 설정 (기본 포트 변경 시)
server:
  port: 8080

# 로깅 레벨 설정 (필요 시)
logging:
  level:
    root: info
    org.springframework.web: debug

#
#app:
#  jwt:
#    secret: { secret }

# AES key
aes:
  secret-key: 0123456789abcdef  # 32바이트 (256비트)

cloud:
  aws:
    credentials:
      access-key: AKIA46ZDFQCUZF7ZSXMA
      secret-key: 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
    region:
      static: ap-northeast-2
    s3:
      bucket: kospot-bucket