{
  "formatVersion": "1.1",
  "component": {
    "group": "org.springframework.boot",
    "module": "spring-boot-starter-webflux",
    "version": "3.4.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.11.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter",
          "version": {
            "requires": "3.4.1"
          }
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-json",
          "version": {
            "requires": "3.4.1"
          }
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-reactor-netty",
          "version": {
            "requires": "3.4.1"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-web",
          "version": {
            "requires": "6.2.1"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-webflux",
          "version": {
            "requires": "6.2.1"
          }
        }
      ],
      "files": [
        {
          "name": "spring-boot-starter-webflux-3.4.1.jar",
          "url": "spring-boot-starter-webflux-3.4.1.jar",
          "size": 4788,
          "sha512": "1d8959b42fd824d7a125e5cbdac32e6ba64f0f42b3d5f94d3f715a18a6cf5830d80bf5855d9f727902e07cd4b1e841627338f0aa2ed0a996bf4d236da364cad7",
          "sha256": "e9cb2c55118cf6ec2d15e9d06b15da762661b051ce717acbe50097404907e74a",
          "sha1": "9d5a081abed454d604c2bbf2ba603f74882e1443",
          "md5": "bb0ee9f0b71003c0881f25fcc132b7aa"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter",
          "version": {
            "requires": "3.4.1"
          }
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-json",
          "version": {
            "requires": "3.4.1"
          }
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-reactor-netty",
          "version": {
            "requires": "3.4.1"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-web",
          "version": {
            "requires": "6.2.1"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-webflux",
          "version": {
            "requires": "6.2.1"
          }
        }
      ],
      "files": [
        {
          "name": "spring-boot-starter-webflux-3.4.1.jar",
          "url": "spring-boot-starter-webflux-3.4.1.jar",
          "size": 4788,
          "sha512": "1d8959b42fd824d7a125e5cbdac32e6ba64f0f42b3d5f94d3f715a18a6cf5830d80bf5855d9f727902e07cd4b1e841627338f0aa2ed0a996bf4d236da364cad7",
          "sha256": "e9cb2c55118cf6ec2d15e9d06b15da762661b051ce717acbe50097404907e74a",
          "sha1": "9d5a081abed454d604c2bbf2ba603f74882e1443",
          "md5": "bb0ee9f0b71003c0881f25fcc132b7aa"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "spring-boot-starter-webflux-3.4.1-javadoc.jar",
          "url": "spring-boot-starter-webflux-3.4.1-javadoc.jar",
          "size": 4788,
          "sha512": "1d8959b42fd824d7a125e5cbdac32e6ba64f0f42b3d5f94d3f715a18a6cf5830d80bf5855d9f727902e07cd4b1e841627338f0aa2ed0a996bf4d236da364cad7",
          "sha256": "e9cb2c55118cf6ec2d15e9d06b15da762661b051ce717acbe50097404907e74a",
          "sha1": "9d5a081abed454d604c2bbf2ba603f74882e1443",
          "md5": "bb0ee9f0b71003c0881f25fcc132b7aa"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "spring-boot-starter-webflux-3.4.1-sources.jar",
          "url": "spring-boot-starter-webflux-3.4.1-sources.jar",
          "size": 4788,
          "sha512": "1d8959b42fd824d7a125e5cbdac32e6ba64f0f42b3d5f94d3f715a18a6cf5830d80bf5855d9f727902e07cd4b1e841627338f0aa2ed0a996bf4d236da364cad7",
          "sha256": "e9cb2c55118cf6ec2d15e9d06b15da762661b051ce717acbe50097404907e74a",
          "sha1": "9d5a081abed454d604c2bbf2ba603f74882e1443",
          "md5": "bb0ee9f0b71003c0881f25fcc132b7aa"
        }
      ]
    }
  ]
}
