{
  "formatVersion": "1.1",
  "component": {
    "group": "io.reactivex.rxjava3",
    "module": "rxjava",
    "version": "3.1.10",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.6.4"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.reactivestreams",
          "module": "reactive-streams",
          "version": {
            "requires": "1.0.4"
          }
        }
      ],
      "files": [
        {
          "name": "rxjava-3.1.10.jar",
          "url": "rxjava-3.1.10.jar",
          "size": 2665366,
          "sha512": "c495dfd8e4dc51d34d221c80245fd61b56e9a6a6f104d15edb5a39a14a6e947a85f5f9d156aa658ebd1451018cdba10ab0fdfb9214a18423ccb29458f4fed512",
          "sha256": "e9f256f9e805572dd5fd45b140db360d7dc444d0c383049b2d3d7ebf05d84aab",
          "sha1": "d980c75b983334eeb9a7ea1a252d044f5e6cdf77",
          "md5": "fb8adba2b37f4bd2d5937231c7db7e34"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.reactivestreams",
          "module": "reactive-streams",
          "version": {
            "requires": "1.0.4"
          }
        }
      ],
      "files": [
        {
          "name": "rxjava-3.1.10.jar",
          "url": "rxjava-3.1.10.jar",
          "size": 2665366,
          "sha512": "c495dfd8e4dc51d34d221c80245fd61b56e9a6a6f104d15edb5a39a14a6e947a85f5f9d156aa658ebd1451018cdba10ab0fdfb9214a18423ccb29458f4fed512",
          "sha256": "e9f256f9e805572dd5fd45b140db360d7dc444d0c383049b2d3d7ebf05d84aab",
          "sha1": "d980c75b983334eeb9a7ea1a252d044f5e6cdf77",
          "md5": "fb8adba2b37f4bd2d5937231c7db7e34"
        }
      ]
    }
  ]
}
