{
  "formatVersion": "1.1",
  "component": {
    "group": "org.springframework.boot",
    "module": "spring-boot-starter-websocket",
    "version": "3.4.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.11.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-web",
          "version": {
            "requires": "3.4.1"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-messaging",
          "version": {
            "requires": "6.2.1"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-websocket",
          "version": {
            "requires": "6.2.1"
          }
        }
      ],
      "files": [
        {
          "name": "spring-boot-starter-websocket-3.4.1.jar",
          "url": "spring-boot-starter-websocket-3.4.1.jar",
          "size": 4783,
          "sha512": "e061c3a3659a2514b167f71e9734d3abe62f147d5d18223ebb0459ecc0b7f8bc712829ec37c369c75c63ac9bd3940117cc650f7714a5bfd539e4a9df2cd832ea",
          "sha256": "2cd4c6e939cc1d6c9b35ed1c7f42ea6b00ebaa04115dad0364e43719768a7f1b",
          "sha1": "88c26a89cce79ed23c782620238f6f222ebf4848",
          "md5": "53a82b6959c038151be862d38a27c641"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-web",
          "version": {
            "requires": "3.4.1"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-messaging",
          "version": {
            "requires": "6.2.1"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-websocket",
          "version": {
            "requires": "6.2.1"
          }
        }
      ],
      "files": [
        {
          "name": "spring-boot-starter-websocket-3.4.1.jar",
          "url": "spring-boot-starter-websocket-3.4.1.jar",
          "size": 4783,
          "sha512": "e061c3a3659a2514b167f71e9734d3abe62f147d5d18223ebb0459ecc0b7f8bc712829ec37c369c75c63ac9bd3940117cc650f7714a5bfd539e4a9df2cd832ea",
          "sha256": "2cd4c6e939cc1d6c9b35ed1c7f42ea6b00ebaa04115dad0364e43719768a7f1b",
          "sha1": "88c26a89cce79ed23c782620238f6f222ebf4848",
          "md5": "53a82b6959c038151be862d38a27c641"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "spring-boot-starter-websocket-3.4.1-javadoc.jar",
          "url": "spring-boot-starter-websocket-3.4.1-javadoc.jar",
          "size": 4783,
          "sha512": "e061c3a3659a2514b167f71e9734d3abe62f147d5d18223ebb0459ecc0b7f8bc712829ec37c369c75c63ac9bd3940117cc650f7714a5bfd539e4a9df2cd832ea",
          "sha256": "2cd4c6e939cc1d6c9b35ed1c7f42ea6b00ebaa04115dad0364e43719768a7f1b",
          "sha1": "88c26a89cce79ed23c782620238f6f222ebf4848",
          "md5": "53a82b6959c038151be862d38a27c641"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "spring-boot-starter-websocket-3.4.1-sources.jar",
          "url": "spring-boot-starter-websocket-3.4.1-sources.jar",
          "size": 4783,
          "sha512": "e061c3a3659a2514b167f71e9734d3abe62f147d5d18223ebb0459ecc0b7f8bc712829ec37c369c75c63ac9bd3940117cc650f7714a5bfd539e4a9df2cd832ea",
          "sha256": "2cd4c6e939cc1d6c9b35ed1c7f42ea6b00ebaa04115dad0364e43719768a7f1b",
          "sha1": "88c26a89cce79ed23c782620238f6f222ebf4848",
          "md5": "53a82b6959c038151be862d38a27c641"
        }
      ]
    }
  ]
}
