{
  "formatVersion": "1.1",
  "component": {
    "group": "org.springframework",
    "module": "spring-messaging",
    "version": "6.2.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.11.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.springframework",
          "module": "spring-beans",
          "version": {
            "requires": "6.2.1"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-core",
          "version": {
            "requires": "6.2.1"
          }
        }
      ],
      "files": [
        {
          "name": "spring-messaging-6.2.1.jar",
          "url": "spring-messaging-6.2.1.jar",
          "size": 617196,
          "sha512": "7508eb7a002fe7aa53332afb5000ecb974f7f253cb4e0315b08875266735ba70f5ae3e61478435d692784198a90273fdf8ec32fd9cde90ce8c7dbe0ecc47f9a8",
          "sha256": "3ff073077c95e605b64d276eecd2bb17e3925dd6401b08c00c3cd86a9ff87d00",
          "sha1": "35335abbdd4b1a781e6ad47d6aaa2c294d62809f",
          "md5": "0c5dd688aefa0950f2dda1a9c7aaa2c4"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.springframework",
          "module": "spring-beans",
          "version": {
            "requires": "6.2.1"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-core",
          "version": {
            "requires": "6.2.1"
          }
        }
      ],
      "files": [
        {
          "name": "spring-messaging-6.2.1.jar",
          "url": "spring-messaging-6.2.1.jar",
          "size": 617196,
          "sha512": "7508eb7a002fe7aa53332afb5000ecb974f7f253cb4e0315b08875266735ba70f5ae3e61478435d692784198a90273fdf8ec32fd9cde90ce8c7dbe0ecc47f9a8",
          "sha256": "3ff073077c95e605b64d276eecd2bb17e3925dd6401b08c00c3cd86a9ff87d00",
          "sha1": "35335abbdd4b1a781e6ad47d6aaa2c294d62809f",
          "md5": "0c5dd688aefa0950f2dda1a9c7aaa2c4"
        }
      ]
    }
  ]
}
