{
  "formatVersion": "1.1",
  "component": {
    "group": "org.springframework",
    "module": "spring-websocket",
    "version": "6.2.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.11.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.springframework",
          "module": "spring-context",
          "version": {
            "requires": "6.2.1"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-core",
          "version": {
            "requires": "6.2.1"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-web",
          "version": {
            "requires": "6.2.1"
          }
        }
      ],
      "files": [
        {
          "name": "spring-websocket-6.2.1.jar",
          "url": "spring-websocket-6.2.1.jar",
          "size": 443090,
          "sha512": "49d7ed519bc7ccfcedf798cbf42ae99ccc91e218ad5e11c3304602e8d939b0d9fdce79599ea37a9662b7496731ffdc3b4897cfd52a11ac0af9e1eddac0a60ff9",
          "sha256": "e3dd2d08f3b0ee685fbd6f2a46d3446a2678db835b7e151b9d4963d39a0579ce",
          "sha1": "bb261d54a16ee6ee29013b28f557bc1c83050656",
          "md5": "3efd720aa1a0b9ced743238dc52df628"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.springframework",
          "module": "spring-context",
          "version": {
            "requires": "6.2.1"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-core",
          "version": {
            "requires": "6.2.1"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-web",
          "version": {
            "requires": "6.2.1"
          }
        }
      ],
      "files": [
        {
          "name": "spring-websocket-6.2.1.jar",
          "url": "spring-websocket-6.2.1.jar",
          "size": 443090,
          "sha512": "49d7ed519bc7ccfcedf798cbf42ae99ccc91e218ad5e11c3304602e8d939b0d9fdce79599ea37a9662b7496731ffdc3b4897cfd52a11ac0af9e1eddac0a60ff9",
          "sha256": "e3dd2d08f3b0ee685fbd6f2a46d3446a2678db835b7e151b9d4963d39a0579ce",
          "sha1": "bb261d54a16ee6ee29013b28f557bc1c83050656",
          "md5": "3efd720aa1a0b9ced743238dc52df628"
        }
      ]
    }
  ]
}
